// packages/solid/src/index.ts
import {
  BoxLayer,
  CandlestickLayer,
  ContourLayer,
  ErrorBarLayer,
  HeatmapLayer,
  HexbinLayer,
  OhlcLayer,
  Plot as CorePlot,
  Plot3D as CorePlot3D,
  PolarPlot as CorePolarPlot,
  QuiverLayer,
  StemLayer,
  type AreaOptions,
  type BarOptions,
  type BoxOptions,
  type CandlestickOptions,
  type ContourOptions,
  type ErrorBarOptions,
  type HeatmapOptions,
  type HexbinOptions,
  type Layer,
  type Annotation as AnnotationSpec,
  type Bar3DOptions,
  type Contour3DOptions,
  type GraphInput,
  type ImageOptions,
  type IsosurfaceOptions,
  type Line3DOptions,
  type LineOptions,
  type OhlcOptions,
  type PatchesOptions,
  type Quiver3DOptions,
  type VolumeOptions,
  type PieOptions,
  type Plot3DOptions,
  type PlotOptions,
  type PointCloudOptions,
  type PolarLineOptions,
  type PolarOptions,
  type PolarScatterOptions,
  type PolarSeries,
  type QuiverOptions,
  type ScatterOptions,
  type StemOptions,
  type SurfaceOptions,
  type YAxisOptions,
} from "@photonviz/core";
import { addGeoJson, addMap, type GeoJsonOptions, type MapOptions } from "@photonviz/map";
import {
  createComponent,
  createContext,
  createEffect,
  createSignal,
  on,
  onCleanup,
  onMount,
  useContext,
  type Accessor,
  type JSX,
} from "solid-js";

// ---------------------------------------------------------------------------
// Reconcile helpers
//
// Solid is fine-grained, so instead of React's effect+deps-array we use `on()`
// with an explicit tracked-props function. Two shapes:
//   • static  — recreate the layer whenever any prop changes.
//   • stream  — recreate on *structural* props; re-upload via setData on *data*
//               props (no teardown), matching the core streaming path.
// The plot accessor is always tracked so a layer registers as soon as its
// container's core Plot exists.
// ---------------------------------------------------------------------------

function bindStatic<L extends Layer>(
  plot: Accessor<CorePlot | null>,
  track: () => readonly unknown[],
  make: (p: CorePlot) => L,
): void {
  createEffect(
    on(
      () => [plot(), ...track()],
      () => {
        const p = plot();
        if (!p) return;
        const l = make(p);
        p.render();
        onCleanup(() => p.removeLayer(l));
      },
    ),
  );
}

function bindStreaming<L extends Layer>(
  plot: Accessor<CorePlot | null>,
  structural: () => readonly unknown[],
  make: (p: CorePlot) => L,
  data: () => readonly unknown[],
  stream: (l: L) => void,
): void {
  let layer: L | null = null;
  createEffect(
    on(
      () => [plot(), ...structural()],
      () => {
        const p = plot();
        if (!p) return;
        const l = make(p);
        layer = l;
        onCleanup(() => {
          p.removeLayer(l);
          layer = null;
        });
      },
    ),
  );
  createEffect(
    on(data, () => {
      const p = plot();
      if (layer && p) {
        stream(layer);
        p.render();
      }
    }),
  );
}

function makeContainer(style?: JSX.CSSProperties, cls?: string): HTMLDivElement {
  const el = document.createElement("div");
  Object.assign(el.style, { position: "relative", width: "100%", height: "100%" });
  if (cls) el.className = cls;
  if (style) for (const k in style) (el.style as unknown as Record<string, unknown>)[k] = style[k as keyof JSX.CSSProperties];
  return el;
}

// ---------------------------------------------------------------------------
// Cartesian plot
// ---------------------------------------------------------------------------

const PlotContext = createContext<Accessor<CorePlot | null>>(() => null);

/** Read the enclosing {@link Plot}'s core instance (an accessor; null until mounted). */
export function usePlot(): Accessor<CorePlot | null> {
  return useContext(PlotContext);
}

export interface PlotProps {
  options?: PlotOptions;
  class?: string;
  style?: JSX.CSSProperties;
  /** Called once with the core `Plot` when it is created. */
  onReady?: (plot: CorePlot) => void;
  children?: JSX.Element;
}

/** Container component. Children (Line, Scatter, …) register once it mounts. */
export function Plot(props: PlotProps): JSX.Element {
  const container = makeContainer(props.style, props.class);
  const [plot, setPlot] = createSignal<CorePlot | null>(null);
  onMount(() => {
    const p = new CorePlot(container, props.options);
    setPlot(p);
    props.onReady?.(p);
  });
  onCleanup(() => plot()?.destroy());
  return [
    container,
    createComponent(PlotContext.Provider, {
      value: plot,
      get children() {
        return props.children;
      },
    }),
  ] as unknown as JSX.Element;
}

export type LineProps = LineOptions;

/** A line series. Streams via `LineLayer.setData(x, y)`. */
export function Line(props: LineProps): JSX.Element {
  const plot = usePlot();
  bindStreaming(
    plot,
    () => [props.color, props.width, props.name, props.yAxis, props.step, props.join, props.miterLimit, props.decimate, props.renderType],
    (p) =>
      p.addLine({
        x: props.x,
        y: props.y,
        color: props.color,
        width: props.width,
        name: props.name,
        yAxis: props.yAxis,
        step: props.step,
        join: props.join,
        miterLimit: props.miterLimit,
        decimate: props.decimate,
        renderType: props.renderType,
      }),
    () => [props.x, props.y],
    (l) => l.setData(props.x, props.y),
  );
  return null;
}

export type ScatterProps = ScatterOptions;

/** A scatter series. Streams via `ScatterLayer.setData(x, y)`. */
export function Scatter(props: ScatterProps): JSX.Element {
  const plot = usePlot();
  bindStreaming(
    plot,
    () => [props.color, props.size, props.marker, props.name, props.yAxis, props.colorBy, props.renderType],
    (p) =>
      p.addScatter({
        x: props.x,
        y: props.y,
        color: props.color,
        size: props.size,
        marker: props.marker,
        name: props.name,
        yAxis: props.yAxis,
        colorBy: props.colorBy,
        renderType: props.renderType,
      }),
    () => [props.x, props.y],
    (l) => l.setData(props.x, props.y),
  );
  return null;
}

export type BarProps = BarOptions;

/** A bar series. Streams via `BarLayer.setData(x, y, base)`. */
export function Bar(props: BarProps): JSX.Element {
  const plot = usePlot();
  bindStreaming(
    plot,
    () => [props.width, props.offset, props.orientation, props.color, props.colors, props.name, props.yAxis, props.renderType],
    (p) =>
      p.addBar({
        x: props.x,
        y: props.y,
        base: props.base,
        width: props.width,
        offset: props.offset,
        orientation: props.orientation,
        color: props.color,
        colors: props.colors,
        name: props.name,
        yAxis: props.yAxis,
        renderType: props.renderType,
      }),
    () => [props.x, props.y, props.base],
    (l) => l.setData(props.x, props.y, props.base),
  );
  return null;
}

export type AreaProps = AreaOptions;

/** An area (filled) series. Streams via `AreaLayer.setData(x, y, base)`. */
export function Area(props: AreaProps): JSX.Element {
  const plot = usePlot();
  bindStreaming(
    plot,
    () => [props.color, props.name, props.yAxis, props.renderType],
    (p) =>
      p.addArea({
        x: props.x,
        y: props.y,
        base: props.base,
        color: props.color,
        name: props.name,
        yAxis: props.yAxis,
        renderType: props.renderType,
      }),
    () => [props.x, props.y, props.base],
    (l) => l.setData(props.x, props.y, props.base),
  );
  return null;
}

export type MapProps = MapOptions;

/** A Web Mercator vector-tile basemap (from `@photonviz/map`). */
export function Map(props: MapProps): JSX.Element {
  const plot = usePlot();
  createEffect(
    on(
      () => [plot(), props.source, props.style, props.bbox, props.maxTiles, props.yAxis],
      () => {
        const p = plot();
        if (!p) return;
        const l = addMap(p, {
          source: props.source,
          style: props.style,
          bbox: props.bbox,
          maxTiles: props.maxTiles,
          yAxis: props.yAxis,
          onUpdate: props.onUpdate,
        });
        onCleanup(() => p.removeLayer(l));
      },
    ),
  );
  return null;
}

export type GeoJsonProps = GeoJsonOptions;

/** A static vector layer rendered from a GeoJSON FeatureCollection. */
export function GeoJson(props: GeoJsonProps): JSX.Element {
  const plot = usePlot();
  createEffect(
    on(
      () => [plot(), props.geojson, props.style, props.layer, props.yAxis],
      () => {
        const p = plot();
        if (!p) return;
        const l = addGeoJson(p, {
          geojson: props.geojson,
          style: props.style,
          layer: props.layer,
          yAxis: props.yAxis,
        });
        onCleanup(() => p.removeLayer(l));
      },
    ),
  );
  return null;
}

export interface YAxisProps extends YAxisOptions {
  id: string;
}

/** Register an additional Y axis. (Core has no live removal, so it persists.) */
export function YAxis(props: YAxisProps): JSX.Element {
  const plot = usePlot();
  createEffect(
    on(
      () => [plot(), props.id],
      () => {
        const p = plot();
        if (!p) return;
        const { id, ...opts } = props;
        p.addYAxis(id, opts);
      },
    ),
  );
  return null;
}

// ---------------------------------------------------------------------------
// Static Cartesian layers
//
// Unlike Line/Scatter/Bar/Area these have no `setData` — they are rebuilt from
// scratch whenever their (structural) props change.
// ---------------------------------------------------------------------------

export type HeatmapProps = HeatmapOptions;

/** A colormapped image of a row-major value grid. Static (rebuilt on change). */
export function Heatmap(props: HeatmapProps): JSX.Element {
  const plot = usePlot();
  bindStatic<HeatmapLayer>(
    plot,
    () => [props.values, props.cols, props.rows, props.extent, props.colormap, props.domain, props.smooth, props.yAxis],
    (p) => p.addHeatmap(props),
  );
  return null;
}

export type BoxProps = BoxOptions;

/** Tukey box-and-whisker / violin groups. Static (rebuilt on change). */
export function Box(props: BoxProps): JSX.Element {
  const plot = usePlot();
  bindStatic<BoxLayer>(
    plot,
    () => [props.groups, props.width, props.box, props.violin, props.yAxis],
    (p) => p.addBox(props),
  );
  return null;
}

export type HexbinProps = HexbinOptions;

/** Hexagonal binning of a point cloud, colored by count. Static. */
export function Hexbin(props: HexbinProps): JSX.Element {
  const plot = usePlot();
  bindStatic<HexbinLayer>(
    plot,
    () => [props.x, props.y, props.radius, props.colormap, props.domain, props.yAxis],
    (p) => p.addHexbin(props),
  );
  return null;
}

export type ContourProps = ContourOptions;

/** Iso-line contours over a row-major value grid. Static. */
export function Contour(props: ContourProps): JSX.Element {
  const plot = usePlot();
  bindStatic<ContourLayer>(
    plot,
    () => [props.values, props.cols, props.rows, props.extent, props.levels, props.color, props.colormap, props.yAxis],
    (p) => p.addContour(props),
  );
  return null;
}

export type ErrorBarProps = ErrorBarOptions;

/** Error bars (whiskers/caps and/or a shaded band). Static. */
export function ErrorBar(props: ErrorBarProps): JSX.Element {
  const plot = usePlot();
  bindStatic<ErrorBarLayer>(
    plot,
    () => [
      props.x,
      props.y,
      props.yerr,
      props.yerrLow,
      props.yerrHigh,
      props.xerr,
      props.color,
      props.width,
      props.capSize,
      props.whiskers,
      props.band,
      props.bandOpacity,
      props.name,
      props.yAxis,
    ],
    (p) => p.addErrorBar(props),
  );
  return null;
}

export type StemProps = StemOptions;

/** Lollipop / stem plot. Static. */
export function Stem(props: StemProps): JSX.Element {
  const plot = usePlot();
  bindStatic<StemLayer>(
    plot,
    () => [props.x, props.y, props.baseline, props.color, props.width, props.markerSize, props.name, props.yAxis],
    (p) => p.addStem(props),
  );
  return null;
}

export type QuiverProps = QuiverOptions;

/** Arrow / vector field. Static. */
export function Quiver(props: QuiverProps): JSX.Element {
  const plot = usePlot();
  bindStatic<QuiverLayer>(
    plot,
    () => [
      props.x,
      props.y,
      props.u,
      props.v,
      props.scale,
      props.color,
      props.width,
      props.headSize,
      props.colorBy,
      props.name,
      props.yAxis,
    ],
    (p) => p.addQuiver(props),
  );
  return null;
}

export type CandlestickProps = CandlestickOptions;

/** OHLC candlestick chart. Static. */
export function Candlestick(props: CandlestickProps): JSX.Element {
  const plot = usePlot();
  bindStatic<CandlestickLayer>(
    plot,
    () => [
      props.x,
      props.open,
      props.high,
      props.low,
      props.close,
      props.width,
      props.upColor,
      props.downColor,
      props.wickWidth,
      props.name,
      props.yAxis,
    ],
    (p) => p.addCandlestick(props),
  );
  return null;
}

export type OhlcProps = OhlcOptions;

/** OHLC bar chart. Static. */
export function Ohlc(props: OhlcProps): JSX.Element {
  const plot = usePlot();
  bindStatic<OhlcLayer>(
    plot,
    () => [
      props.x,
      props.open,
      props.high,
      props.low,
      props.close,
      props.width,
      props.upColor,
      props.downColor,
      props.lineWidth,
      props.name,
      props.yAxis,
    ],
    (p) => p.addOhlc(props),
  );
  return null;
}

export type PieProps = PieOptions;

/** A pie / donut chart. Set the plot's `equalAspect` so it stays circular. Static. */
export function Pie(props: PieProps): JSX.Element {
  const plot = usePlot();
  bindStatic(
    plot,
    () => [
      props.values,
      props.colors,
      props.colormap,
      props.center,
      props.radius,
      props.innerRadius,
      props.startAngle,
      props.name,
      props.yAxis,
    ],
    (p) => p.addPie(props),
  );
  return null;
}

export type PatchesProps = PatchesOptions;

/** Filled polygons (choropleth-capable), triangulated with earcut. Static. */
export function Patches(props: PatchesProps): JSX.Element {
  const plot = usePlot();
  bindStatic(
    plot,
    () => [props.patches, props.color, props.colormap, props.domain, props.opacity, props.name, props.yAxis],
    (p) => p.addPatches(props),
  );
  return null;
}

export type ImageProps = ImageOptions;

/** An RGBA image / URL over a data-space extent. Static. */
export function Image(props: ImageProps): JSX.Element {
  const plot = usePlot();
  bindStatic(
    plot,
    () => [props.source, props.extent, props.smooth, props.opacity, props.name, props.yAxis],
    (p) => p.addImage(props),
  );
  return null;
}

export type GraphProps = GraphInput;

/** A node-link graph (auto force-layout when positions are omitted). Static. */
export function Graph(props: GraphProps): JSX.Element {
  const plot = usePlot();
  bindStatic(
    plot,
    () => [props.x, props.y, props.edges, props.nodes, props.nodeColor, props.edgeColor, props.nodeSize, props.name, props.yAxis],
    (p) => p.addGraph(props),
  );
  return null;
}

export type AnnotationProps = AnnotationSpec;

/** A span / band / box / label annotation drawn above the data. */
export function Annotation(props: AnnotationProps): JSX.Element {
  const plot = usePlot();
  createEffect(
    on(
      () => [plot(), JSON.stringify(props)],
      () => {
        const p = plot();
        if (!p) return;
        onCleanup(p.addAnnotation({ ...props } as AnnotationSpec));
      },
    ),
  );
  return null;
}

// ---------------------------------------------------------------------------
// Polar plot
//
// A separate core class with its own container + context. `PolarPlot` has no
// `removeLayer`, so child cleanup is a no-op (the series lives until the plot
// is destroyed).
// ---------------------------------------------------------------------------

const PolarContext = createContext<Accessor<CorePolarPlot | null>>(() => null);

/** Read the enclosing {@link PolarPlot}'s core instance (an accessor). */
export function usePolarPlot(): Accessor<CorePolarPlot | null> {
  return useContext(PolarContext);
}

export interface PolarPlotProps {
  options?: PolarOptions;
  class?: string;
  style?: JSX.CSSProperties;
  onReady?: (plot: CorePolarPlot) => void;
  children?: JSX.Element;
}

/** Container for a polar (θ, r) plot. Children (PolarLine, PolarScatter) register once it mounts. */
export function PolarPlot(props: PolarPlotProps): JSX.Element {
  const container = makeContainer(props.style, props.class);
  const [plot, setPlot] = createSignal<CorePolarPlot | null>(null);
  onMount(() => {
    const p = new CorePolarPlot(container, props.options);
    setPlot(p);
    props.onReady?.(p);
  });
  onCleanup(() => plot()?.destroy());
  return [
    container,
    createComponent(PolarContext.Provider, {
      value: plot,
      get children() {
        return props.children;
      },
    }),
  ] as unknown as JSX.Element;
}

export type PolarLineProps = PolarLineOptions;

/** A polar line series. Streams via `PolarSeries.setData(theta, r)`. */
export function PolarLine(props: PolarLineProps): JSX.Element {
  const plot = usePolarPlot();
  let series: PolarSeries | null = null;
  createEffect(
    on(
      () => [plot(), props.color, props.width, props.closed],
      () => {
        const p = plot();
        if (!p) return;
        series = p.addLine({ theta: props.theta, r: props.r, color: props.color, width: props.width, closed: props.closed });
        // PolarPlot has no removeLayer → nothing to clean up (series persists).
        onCleanup(() => {
          series = null;
        });
      },
    ),
  );
  createEffect(
    on(
      () => [props.theta, props.r],
      () => series?.setData(props.theta, props.r),
    ),
  );
  return null;
}

export type PolarScatterProps = PolarScatterOptions;

/** A polar scatter series. Streams via `PolarSeries.setData(theta, r)`. */
export function PolarScatter(props: PolarScatterProps): JSX.Element {
  const plot = usePolarPlot();
  let series: PolarSeries | null = null;
  createEffect(
    on(
      () => [plot(), props.color, props.size, props.labels],
      () => {
        const p = plot();
        if (!p) return;
        series = p.addScatter({ theta: props.theta, r: props.r, color: props.color, size: props.size, labels: props.labels });
        onCleanup(() => {
          series = null;
        });
      },
    ),
  );
  createEffect(
    on(
      () => [props.theta, props.r],
      () => series?.setData(props.theta, props.r),
    ),
  );
  return null;
}

// ---------------------------------------------------------------------------
// 3D plot
//
// A separate core class with its own container + context. `Plot3D` has no
// layer-removal API, so child cleanup is a no-op (layers live until the plot
// is destroyed).
// ---------------------------------------------------------------------------

const Plot3DContext = createContext<Accessor<CorePlot3D | null>>(() => null);

/** Read the enclosing {@link Plot3D}'s core instance (an accessor). */
export function usePlot3D(): Accessor<CorePlot3D | null> {
  return useContext(Plot3DContext);
}

export interface Plot3DProps {
  options?: Plot3DOptions;
  class?: string;
  style?: JSX.CSSProperties;
  onReady?: (plot: CorePlot3D) => void;
  children?: JSX.Element;
}

/** Container for a 3D plot with an orbit camera. Children (Surface, PointCloud) register once it mounts. */
export function Plot3D(props: Plot3DProps): JSX.Element {
  const container = makeContainer(props.style, props.class);
  const [plot, setPlot] = createSignal<CorePlot3D | null>(null);
  onMount(() => {
    const p = new CorePlot3D(container, props.options);
    setPlot(p);
    props.onReady?.(p);
  });
  onCleanup(() => plot()?.destroy());
  return [
    container,
    createComponent(Plot3DContext.Provider, {
      value: plot,
      get children() {
        return props.children;
      },
    }),
  ] as unknown as JSX.Element;
}

export type SurfaceProps = SurfaceOptions;

/** A 3D height-field surface. Static — Plot3D has no removal API (no-op cleanup). */
export function Surface(props: SurfaceProps): JSX.Element {
  const plot = usePlot3D();
  createEffect(
    on(
      () => [plot(), props.values, props.cols, props.rows, props.extentX, props.extentZ, props.colormap],
      () => {
        const p = plot();
        if (!p) return;
        // Plot3D has no layer removal → nothing to clean up (layer persists).
        p.addSurface(props);
      },
    ),
  );
  return null;
}

export type PointCloudProps = PointCloudOptions;

/** A 3D point cloud. Static — Plot3D has no removal API (no-op cleanup). */
export function PointCloud(props: PointCloudProps): JSX.Element {
  const plot = usePlot3D();
  createEffect(
    on(
      () => [plot(), props.x, props.y, props.z, props.color, props.size, props.sizes, props.colorBy, props.labels, props.name],
      () => {
        const p = plot();
        if (!p) return;
        const l = p.addPointCloud(props);
        onCleanup(() => p.removeLayer(l));
      },
    ),
  );
  return null;
}

export type Line3DProps = Line3DOptions;

/** A 3D polyline / path. Static — Plot3D has no removal API. */
export function Line3D(props: Line3DProps): JSX.Element {
  const plot = usePlot3D();
  createEffect(
    on(
      () => [plot(), props.x, props.y, props.z, props.color, props.name],
      () => {
        const p = plot();
        if (!p) return;
        p.addLine3D(props);
      },
    ),
  );
  return null;
}

export type Bar3DProps = Bar3DOptions;

/** 3D bars on an x/z grid. Static — Plot3D has no removal API. */
export function Bar3D(props: Bar3DProps): JSX.Element {
  const plot = usePlot3D();
  createEffect(
    on(
      () => [plot(), props.x, props.y, props.z, props.width, props.color, props.colorBy, props.name],
      () => {
        const p = plot();
        if (!p) return;
        p.addBar3D(props);
      },
    ),
  );
  return null;
}

export type Quiver3DProps = Quiver3DOptions;

/** A 3D vector field. Static — Plot3D has no removal API. */
export function Quiver3D(props: Quiver3DProps): JSX.Element {
  const plot = usePlot3D();
  createEffect(
    on(
      () => [plot(), props.x, props.y, props.z, props.u, props.v, props.w, props.scale, props.color, props.colorBy, props.headSize, props.name],
      () => {
        const p = plot();
        if (!p) return;
        p.addQuiver3D(props);
      },
    ),
  );
  return null;
}

export type Contour3DProps = Contour3DOptions;

/** 3D iso-height contour lines. Static — Plot3D has no removal API. */
export function Contour3D(props: Contour3DProps): JSX.Element {
  const plot = usePlot3D();
  createEffect(
    on(
      () => [plot(), props.values, props.cols, props.rows, props.extentX, props.extentZ, props.levels, props.color, props.colormap, props.name],
      () => {
        const p = plot();
        if (!p) return;
        p.addContour3D(props);
      },
    ),
  );
  return null;
}

export type IsosurfaceProps = IsosurfaceOptions;

/** A marching-cubes isosurface of a 3D scalar volume. Static. */
export function Isosurface(props: IsosurfaceProps): JSX.Element {
  const plot = usePlot3D();
  createEffect(
    on(
      () => [plot(), props.values, props.dims, props.isoLevel, props.extent, props.color, props.opacity, props.name],
      () => {
        const p = plot();
        if (!p) return;
        const l = p.addIsosurface(props);
        onCleanup(() => p.removeLayer(l));
      },
    ),
  );
  return null;
}

export type VolumeProps = VolumeOptions;

/** Direct volume rendering (GPU raymarch) of a 3D scalar field. Static. */
export function Volume(props: VolumeProps): JSX.Element {
  const plot = usePlot3D();
  createEffect(
    on(
      () => [plot(), props.values, props.dims, props.extent, props.colormap, props.domain, props.density, props.name],
      () => {
        const p = plot();
        if (!p) return;
        const l = p.addVolume(props);
        onCleanup(() => p.removeLayer(l));
      },
    ),
  );
  return null;
}

// packages/wc/src/index.ts
/**
 * @photonviz/wc — framework-agnostic Web Components (custom elements) for Photon.
 *
 * Three elements are registered on import: `<photon-plot>` (Cartesian),
 * `<photon-plot3d>` (3D), and `<photon-polar>` (polar). Configure them by
 * assigning JS properties on the element (`series`, `options`, `layers`, …);
 * the `theme` and `height` attributes are also honoured.
 *
 *   const el = document.querySelector("photon-plot");
 *   el.series = [{ type: "line", x, y, color: "#60a5fa" }];
 */
import {
  AreaLayer,
  BarLayer,
  LineLayer,
  Plot as CorePlot,
  Plot3D as CorePlot3D,
  PolarPlot as CorePolarPlot,
  ScatterLayer,
  addHeikinAshi,
  addRenko,
  addVolumeProfile,
} from "@photonviz/core";
import type {
  Annotation,
  AreaOptions,
  Bar3DOptions,
  BarOptions,
  BoxOptions,
  CandlestickOptions,
  Contour3DOptions,
  ContourOptions,
  ErrorBarOptions,
  GraphInput,
  HeatmapOptions,
  HeikinAshiOptions,
  HexbinOptions,
  ImageOptions,
  IsosurfaceOptions,
  Layer,
  Line3DOptions,
  LineOptions,
  OhlcOptions,
  PatchesOptions,
  PieOptions,
  Plot3DOptions,
  PlotOptions,
  PointCloudOptions,
  PolarLineOptions,
  PolarOptions,
  PolarScatterOptions,
  PolarSeries,
  Quiver3DOptions,
  QuiverOptions,
  RenkoOptions,
  ScatterOptions,
  StemOptions,
  SurfaceOptions,
  VolumeOptions,
  VolumeProfileOptions,
  YAxisOptions,
} from "@photonviz/core";
import { addGeoJson, addMap } from "@photonviz/map";
import type { GeoJsonOptions, MapOptions } from "@photonviz/map";

// --- Cartesian series --------------------------------------------------------

/** A single Cartesian series, discriminated by `type`. */
export type SeriesSpec =
  | ({ type: "line" } & LineOptions)
  | ({ type: "scatter" } & ScatterOptions)
  | ({ type: "bar" } & BarOptions)
  | ({ type: "area" } & AreaOptions)
  | ({ type: "heatmap" } & HeatmapOptions)
  | ({ type: "box" } & BoxOptions)
  | ({ type: "hexbin" } & HexbinOptions)
  | ({ type: "contour" } & ContourOptions)
  | ({ type: "errorbar" } & ErrorBarOptions)
  | ({ type: "stem" } & StemOptions)
  | ({ type: "quiver" } & QuiverOptions)
  | ({ type: "candlestick" } & CandlestickOptions)
  | ({ type: "ohlc" } & OhlcOptions)
  | ({ type: "heikinAshi" } & HeikinAshiOptions)
  | ({ type: "renko" } & RenkoOptions)
  | ({ type: "volumeProfile" } & VolumeProfileOptions)
  | ({ type: "pie" } & PieOptions)
  | ({ type: "patches" } & PatchesOptions)
  | ({ type: "image" } & ImageOptions)
  | ({ type: "graph" } & GraphInput)
  | ({ type: "map" } & MapOptions)
  | ({ type: "geojson" } & GeoJsonOptions);

export interface YAxisSpec extends YAxisOptions {
  id: string;
}

function addSeries(p: CorePlot, s: SeriesSpec): Layer {
  switch (s.type) {
    case "line": return p.addLine(s);
    case "scatter": return p.addScatter(s);
    case "bar": return p.addBar(s);
    case "area": return p.addArea(s);
    case "heatmap": return p.addHeatmap(s);
    case "box": return p.addBox(s);
    case "hexbin": return p.addHexbin(s);
    case "contour": return p.addContour(s);
    case "errorbar": return p.addErrorBar(s);
    case "stem": return p.addStem(s);
    case "quiver": return p.addQuiver(s);
    case "candlestick": return p.addCandlestick(s);
    case "ohlc": return p.addOhlc(s);
    case "heikinAshi": return addHeikinAshi(p, s);
    case "renko": return addRenko(p, s);
    case "volumeProfile": return addVolumeProfile(p, s);
    case "pie": return p.addPie(s);
    case "patches": return p.addPatches(s);
    case "image": return p.addImage(s);
    case "graph": return p.addGraph(s);
    case "map": return addMap(p, s);
    case "geojson": return addGeoJson(p, s);
  }
}

/** Re-upload data for a streaming series (line/scatter/bar/area); others static. */
function updateSeries(layer: Layer, s: SeriesSpec): void {
  switch (s.type) {
    case "line": (layer as LineLayer).setData(s.x, s.y); break;
    case "scatter": (layer as ScatterLayer).setData(s.x, s.y); break;
    case "bar": (layer as BarLayer).setData(s.x, s.y, s.base); break;
    case "area": (layer as AreaLayer).setData(s.x, s.y, s.base); break;
    default: break; // static — nothing to stream
  }
}

// --- Polar -------------------------------------------------------------------

export type PolarSeriesSpec =
  | ({ type: "line" } & PolarLineOptions)
  | ({ type: "scatter" } & PolarScatterOptions);

function addPolarSeries(p: CorePolarPlot, s: PolarSeriesSpec): PolarSeries {
  switch (s.type) {
    case "line": return p.addLine(s);
    case "scatter": return p.addScatter(s);
  }
}

// --- 3D ----------------------------------------------------------------------

export type LayerSpec3D =
  | ({ type: "surface" } & SurfaceOptions)
  | ({ type: "pointcloud" } & PointCloudOptions)
  | ({ type: "line3d" } & Line3DOptions)
  | ({ type: "bar3d" } & Bar3DOptions)
  | ({ type: "quiver3d" } & Quiver3DOptions)
  | ({ type: "contour3d" } & Contour3DOptions)
  | ({ type: "isosurface" } & IsosurfaceOptions)
  | ({ type: "volume" } & VolumeOptions);

function addLayer3D(p: CorePlot3D, s: LayerSpec3D): void {
  switch (s.type) {
    case "surface": p.addSurface(s); break;
    case "pointcloud": p.addPointCloud(s); break;
    case "line3d": p.addLine3D(s); break;
    case "bar3d": p.addBar3D(s); break;
    case "quiver3d": p.addQuiver3D(s); break;
    case "contour3d": p.addContour3D(s); break;
    case "isosurface": p.addIsosurface(s); break;
    case "volume": p.addVolume(s); break;
  }
}

// --- Shared element scaffolding ---------------------------------------------

const HOST_CSS =
  ":host{display:block;height:320px;position:relative}" +
  ".photon-root{width:100%;height:100%}";

/** Build the shadow root once, returning the container the plot mounts into. */
function mountShadow(host: HTMLElement): HTMLDivElement {
  const root = host.shadowRoot ?? host.attachShadow({ mode: "open" });
  root.replaceChildren();
  const style = document.createElement("style");
  style.textContent = HOST_CSS;
  const container = document.createElement("div");
  container.className = "photon-root";
  root.append(style, container);
  return container;
}

/** Apply a `height` attribute value (e.g. "480px", "50vh") to the host. */
function applyHeight(host: HTMLElement, value: string | null): void {
  host.style.height = value ?? "";
}

/** Merge a `theme` attribute ("dark"/"light") into a plot options object. */
function withThemeAttr<T extends { theme?: unknown }>(host: HTMLElement, options: T): T {
  const theme = host.getAttribute("theme");
  if (theme === "dark" || theme === "light") return { ...options, theme };
  return options;
}

// --- <photon-plot> -----------------------------------------------------------

/**
 * `<photon-plot>` — Cartesian plot. Configure via JS properties:
 * `options`, `series`, `yAxes`, `annotations`. Attributes: `theme`, `height`.
 */
export class PhotonPlotElement extends HTMLElement {
  static readonly observedAttributes = ["theme", "height"];

  #plot: CorePlot | undefined;
  #container: HTMLDivElement | undefined;
  #layers: Layer[] = [];

  #options: PlotOptions = {};
  #series: SeriesSpec[] = [];
  #yAxes: YAxisSpec[] = [];
  #annotations: Annotation[] = [];

  get options(): PlotOptions { return this.#options; }
  set options(v: PlotOptions | undefined) { this.#options = v ?? {}; this.#rebuild(); }

  get series(): SeriesSpec[] { return this.#series; }
  set series(v: SeriesSpec[] | undefined) {
    const next = v ?? [];
    const prev = this.#series;
    this.#series = next;
    if (!this.#plot) return;
    // Same count → stream data through the existing layers; else rebuild.
    if (next.length === prev.length && next.every((s, i) => s.type === prev[i]!.type)) {
      for (let i = 0; i < this.#layers.length; i++) updateSeries(this.#layers[i]!, next[i]!);
      this.#plot.render();
    } else {
      this.#buildSeries();
    }
  }

  get yAxes(): YAxisSpec[] { return this.#yAxes; }
  set yAxes(v: YAxisSpec[] | undefined) { this.#yAxes = v ?? []; this.#rebuild(); }

  get annotations(): Annotation[] { return this.#annotations; }
  set annotations(v: Annotation[] | undefined) {
    this.#annotations = v ?? [];
    if (!this.#plot) return;
    this.#plot.clearAnnotations();
    for (const a of this.#annotations) this.#plot.addAnnotation(a);
  }

  connectedCallback(): void { this.#mount(); }
  disconnectedCallback(): void { this.#unmount(); }

  attributeChangedCallback(name: string, _old: string | null, value: string | null): void {
    if (name === "height") applyHeight(this, value);
    else if (name === "theme") this.#rebuild();
  }

  #mount(): void {
    this.#container = mountShadow(this);
    applyHeight(this, this.getAttribute("height"));
    this.#plot = new CorePlot(this.#container, withThemeAttr(this, this.#options));
    for (const ya of this.#yAxes) this.#plot.addYAxis(ya.id, ya);
    this.#buildSeries();
    for (const a of this.#annotations) this.#plot.addAnnotation(a);
  }

  #buildSeries(): void {
    if (!this.#plot) return;
    for (const l of this.#layers) this.#plot.removeLayer(l);
    this.#layers = this.#series.map((s) => addSeries(this.#plot!, s));
  }

  #unmount(): void {
    this.#plot?.destroy();
    this.#plot = undefined;
    this.#layers = [];
    this.#container = undefined;
  }

  /** Rebuild the whole plot in place (used when options/axes/theme change). */
  #rebuild(): void {
    if (!this.isConnected) return;
    this.#unmount();
    this.#mount();
  }
}

// --- <photon-plot3d> ---------------------------------------------------------

/**
 * `<photon-plot3d>` — 3D plot. Configure via JS properties: `options`, `layers`.
 * Attributes: `theme`, `height`.
 */
export class PhotonPlot3DElement extends HTMLElement {
  // Plot3DOptions has no `theme`; only `height` is reflected here.
  static readonly observedAttributes = ["height"];

  #plot: CorePlot3D | undefined;
  #container: HTMLDivElement | undefined;
  #options: Plot3DOptions = {};
  #layers: LayerSpec3D[] = [];

  get options(): Plot3DOptions { return this.#options; }
  set options(v: Plot3DOptions | undefined) { this.#options = v ?? {}; this.#rebuild(); }

  get layers(): LayerSpec3D[] { return this.#layers; }
  set layers(v: LayerSpec3D[] | undefined) { this.#layers = v ?? []; this.#rebuild(); }

  connectedCallback(): void { this.#mount(); }
  disconnectedCallback(): void { this.#unmount(); }

  attributeChangedCallback(name: string, _old: string | null, value: string | null): void {
    if (name === "height") applyHeight(this, value);
  }

  #mount(): void {
    this.#container = mountShadow(this);
    applyHeight(this, this.getAttribute("height"));
    this.#plot = new CorePlot3D(this.#container, this.#options);
    for (const l of this.#layers) addLayer3D(this.#plot, l);
  }

  #unmount(): void {
    this.#plot?.destroy();
    this.#plot = undefined;
    this.#container = undefined;
  }

  #rebuild(): void {
    if (!this.isConnected) return;
    this.#unmount();
    this.#mount();
  }
}

// --- <photon-polar> ----------------------------------------------------------

/**
 * `<photon-polar>` — polar plot. Configure via JS properties: `options`,
 * `series` (`line` / `scatter`). Attributes: `theme`, `height`.
 */
export class PhotonPolarElement extends HTMLElement {
  static readonly observedAttributes = ["theme", "height"];

  #plot: CorePolarPlot | undefined;
  #container: HTMLDivElement | undefined;
  #series: PolarSeries[] = [];
  #options: PolarOptions = {};
  #specs: PolarSeriesSpec[] = [];

  get options(): PolarOptions { return this.#options; }
  set options(v: PolarOptions | undefined) { this.#options = v ?? {}; this.#rebuild(); }

  get series(): PolarSeriesSpec[] { return this.#specs; }
  set series(v: PolarSeriesSpec[] | undefined) {
    const next = v ?? [];
    const prev = this.#specs;
    this.#specs = next;
    if (!this.#plot) return;
    // PolarPlot has no removeLayer; stream when the shape matches, else rebuild.
    if (next.length === prev.length && next.every((s, i) => s.type === prev[i]!.type)) {
      for (let i = 0; i < this.#series.length; i++) this.#series[i]!.setData(next[i]!.theta, next[i]!.r);
    } else {
      this.#rebuild();
    }
  }

  connectedCallback(): void { this.#mount(); }
  disconnectedCallback(): void { this.#unmount(); }

  attributeChangedCallback(name: string, _old: string | null, value: string | null): void {
    if (name === "height") applyHeight(this, value);
    else if (name === "theme") this.#rebuild();
  }

  #mount(): void {
    this.#container = mountShadow(this);
    applyHeight(this, this.getAttribute("height"));
    this.#plot = new CorePolarPlot(this.#container, withThemeAttr(this, this.#options));
    this.#series = this.#specs.map((s) => addPolarSeries(this.#plot!, s));
  }

  #unmount(): void {
    this.#plot?.destroy();
    this.#plot = undefined;
    this.#series = [];
    this.#container = undefined;
  }

  #rebuild(): void {
    if (!this.isConnected) return;
    this.#unmount();
    this.#mount();
  }
}

// --- Registration ------------------------------------------------------------

/** Register all three custom elements. Safe to call multiple times. */
export function defineElements(): void {
  if (typeof customElements === "undefined") return;
  if (!customElements.get("photon-plot")) customElements.define("photon-plot", PhotonPlotElement);
  if (!customElements.get("photon-plot3d")) customElements.define("photon-plot3d", PhotonPlot3DElement);
  if (!customElements.get("photon-polar")) customElements.define("photon-polar", PhotonPolarElement);
}

// Auto-register on import (no-op in non-DOM environments).
if (typeof customElements !== "undefined") defineElements();

declare global {
  interface HTMLElementTagNameMap {
    "photon-plot": PhotonPlotElement;
    "photon-plot3d": PhotonPlot3DElement;
    "photon-polar": PhotonPolarElement;
  }
}
